# Generated by Django 3.2.9 on 2021-12-19 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housemates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='members',
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='housemates.house'),
        ),
    ]
