# Generated by Django 3.2.9 on 2021-11-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as superuser.', verbose_name='superuser status'),
        ),
    ]
