# Generated by Django 3.2.9 on 2021-12-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='invite_type',
            field=models.CharField(choices=[('BILL_INVITE', 'Bill invte'), ('HOUSE_INVITE', 'House invite'), ('EVENT_INVITE', 'Event invite')], max_length=15),
        ),
    ]
