# Generated by Django 3.2.9 on 2021-12-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemates', '0003_item_previous_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
